environment:
  matrix:
    - PYTHON: "C:\\Python35-x64"
      PYTHON_VERSION: "3.5.3"
      PYTHON_ARCH: "64"
platform: x86
configuration: Release
init:
  - cmd: ECHO Processor architecture - %PROCESSOR_ARCHITECTURE%
  - cmd: wmic OS get OSArchitecture

  # As AppVeyor has multiple python install, verify which one uses by default
  - cmd: ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%
  - cmd: python --version
  - cmd: python -c "import struct; print(struct.calcsize('P') * 8)"

  # Set the relevant python and pip location to the path
  - cmd: set PATH=%PYTHON%;%PYTHON%\scripts;%PATH%
  - cmd: ECHO Path - %PATH%

  # Verify the new default python
  - cmd: python --version
  - cmd: pip --version

  # Check out installed python packages
  - cmd: pip freeze

install:
  # Install InnoSetup and add to path
  # Copied from
  # https://github.com/Phonations/Joker/blob/master/appveyor.yml
  - choco install -y InnoSetup

  # Install python dependencies
  - cmd: pip install -r requirements.txt

  # Check installed packages again
  - cmd: pip freeze

  # Build mu using PyInstaller and rename executable with timestamp
  - cmd: pyinstaller specs/indows_launcher.spec --name launcher --onefile --log-level=DEBUG --debug
  - cmd: pyinstaller specs/windows_launcher_dir.spec --name launcher --onedir --log-level=DEBUG --debug --distpath=dir_dist

  # Create InnoSetup installers
  # Set InnoSetup path here, because Cython complained about it.
  - set PATH=%PATH%;"C:\\Program Files (x86)\\Inno Setup 5"
  - iscc /Q install/setup.iss

  # Deploy results
  - cmd: ./scripts/deploy_win.bat

# Not a project with an msbuild file, build done at install.
build: off
artifacts:
  - path: dist\**\*
    name: dist
  - path: dir_dist
