language: python
matrix:
  include:
    # Use the built in venv for linux builds
    - os: linux
      sudo: required
      python: 3.5
      cache: pip
    # Use generic language for osx
    - os: osx
      language: generic
      before_install:
        # Install Python 3.5.2 only
        # Normal brew install gets 3.6.x which is incompatible
        - brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/ec545d45d4512ace3570782283df4ecda6bb0044/Formula/python3.rb
        - virtualenv venv -p python3
        - source venv/bin/activate
env:
  global:
    - PYTHONPATH="$TRAVIS_BUILD_DIR/src"
# Perform the manual steps on osx to install python3 and activate venv
install:
  - python --version
  - echo $PYTHONPATH
  # install dependencies
  - pip install -r requirements.txt
  # install testing tools
  - pip install coverage
  - pip install coveralls
  - pip install pep8
script:
  # PEP8 Style Checks
  - pep8 --show-source src/ test/
  # Run tests and collect coverage information
  - coverage run --source=src/ -m unittest discover -v -s test
  # Run PyInstaller build
  - pyinstaller launcher.spec --name launcher --onefile
after_success:
  coveralls
