language: python
matrix:
  include:
    # Use the built in venv for linux builds
    - os: linux
      sudo: required
      python: 3.5
      cache: pip
    # Use generic language for osx
    - os: osx
      language: generic
env:
  global:
    - PYTHONPATH="$TRAVIS_BUILD_DIR/src"
# Perform the manual steps on osx to install python3 and activate venv
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update                ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install python3       ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then virtualenv venv -p python3 ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source venv/bin/activate   ; fi
install:
  - python --version
  - echo $PYTHONPATH
  # install dependencies
  - pip install -r requirements.txt
  # install testing tools
  - pip install coverage
  - pip install coveralls
  - pip install pep8
script:
  # PEP8 Style Checks
  - pep8 --show-source src/ test/
  # Run tests and collect coverage information
  - coverage run --source=src/ -m unittest discover -v -s test
  # Run PyInstaller build
  - pyinstaller launcher.spec --name launcher --onefile
after_success:
  coveralls
