language: python
matrix:
  include:
    # Use the built in venv for linux builds
    - os: linux
      sudo: required
      python: 3.5
      cache: pip
      dist: trusty
      sudo: false
    # Use generic language for osx
    - os: osx
      language: generic
      cache: pip
      before_install:
        - brew update
        # Install Python 3.5.2 only
        # Normal brew install gets 3.6.x which is incompatible
        - brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/ec545d45d4512ace3570782283df4ecda6bb0044/Formula/python3.rb
        - virtualenv venv -p python3
        - source venv/bin/activate
        - which pip
        - pip install six wheel
env:
  global:
    - PYTHONPATH="$TRAVIS_BUILD_DIR/src;$TRAVIS_BUILD_DIR/test"
# Perform the manual steps on osx to install python3 and activate venv
install:
  # install dependencies
  - pip install -r requirements.txt
  # Test dev version of PyInstaller
  - pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
  # install testing tools
  - pip install coverage coveralls pep8
script:
  # PEP8 Style Checks
  - pep8 --show-source src/ test/
  # Run tests and collect coverage information
  - nosetests --with-coverage --cover-package=src --cover-html
  # Run PyInstaller build
  - pyinstaller specs/launcher.spec --name launcher --onefile --log-level=DEBUG
after_success:
  coveralls
deploy:
  - provider: script
    script: curl -i -X POST $DEPLOY_BASE_URL/$TRAVIS_BRANCH/$TRAVIS_OS_NAME?token=$TOKEN
    skip_cleanup: true
    on:
      branch:
        - config
        - master
  - provider: script
    script: ./scripts/deploy.sh
    skip_cleanup: true
    on:
      branch: master
